services:
#    app_cofidur.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  app_cofidur.password_resetting:
      class: AppBundle\EventListener\PasswordResettingListener
      arguments: ['@router']
      tags:
          - { name: kernel.event_subscriber }

  app_cofidur.historisationskillmatrix:
      class: AppBundle\Services\HistorisationSkillMatrix
 #     arguments: ['@doctrine.orm.entity_manager']
 # app_cofidur.service.role:
 #       class: AppBundle\Services\RoleService
 #       arguments: [@security.role_hierarchy]

 # app_cofidur.greet_command:
 #     class: AppBundle\Command\GreetCommand
 #     name: 'mycommand:start'
 #     tags:
 #         - { name: console.command }
