services:
#    app_cofidur.example:
#        class: AppBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  app_cofidur.password_resetting:
      class: AppBundle\EventListener\PasswordResettingListener
      arguments: ['@router']
      tags:
          - { name: kernel.event_subscriber }
       
 # app_cofidur.skillmatrix:
 #     class: AppBundle\Services\SkillMatrixService
 #     arguments: ['@doctrine.orm.entity_manager']
